pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent{
    docker { image 'maven:3.8.1-adoptopenjdk-11' }
    }
    steps {
      sh 'mvn --version'
     }
    }
  stages('Front-end') {
    agent {
      docer { iamge 'node:16-alphine' }
    }
    steps {
      sh 'node --version'
    }
  }
    stage('DB') {
      agent {
        docker { image 'mysql:latest' }
      }
      steps {
        sh 'SELECT * FROM XYZ'
      }
    }
   }
  
  }
